# Generated by Django 3.1.5 on 2021-01-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to='videos/%Y/%m/%d')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
