# Generated by Django 3.1.5 on 2021-01-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
