# Generated by Django 3.1.5 on 2021-01-17 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_videomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드 날짜'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='videoname',
            field=models.CharField(max_length=200),
        ),
    ]
