# Generated by Django 3.1.5 on 2021-01-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_auto_20210117_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='des',
            field=models.TextField(null=True, verbose_name='동영상 설명'),
        ),
    ]
