# Generated by Django 3.1.5 on 2021-01-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_videomodel_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='uploaded_at',
            field=models.DateTimeField(verbose_name='업로드 날짜'),
        ),
    ]
