# Generated by Django 3.1.5 on 2021-01-17 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_auto_20210117_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드 날짜'),
        ),
    ]
