# Generated by Django 3.1.5 on 2021-01-20 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_auto_20210117_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videomodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
