# Generated by Django 3.1.5 on 2021-01-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_auto_20210120_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
