# Generated by Django 3.1.5 on 2021-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube', '0011_delete_videomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='video')),
                ('des', models.CharField(max_length=1000)),
            ],
        ),
    ]
