# Generated by Django 3.1.5 on 2021-01-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_auto_20210121_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='des',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='video/'),
        ),
    ]
