# Generated by Django 3.1.5 on 2021-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0019_auto_20210121_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
