# Generated by Django 3.1.5 on 2021-01-21 10:58

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0020_auto_20210121_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='video'),
        ),
    ]
