# Generated by Django 3.1.5 on 2021-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0022_auto_20210121_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
