# Generated by Django 3.1.5 on 2021-01-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0023_auto_20210121_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='des',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='video/'),
        ),
    ]
