# Generated by Django 3.1.5 on 2021-01-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0025_auto_20210122_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
