# Generated by Django 3.1.5 on 2021-01-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0031_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
