# Generated by Django 3.1.5 on 2021-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0034_auto_20210127_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_count',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글수'),
        ),
    ]
