# Generated by Django 3.1.5 on 2021-01-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0035_comment_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='댓글수'),
        ),
    ]
