# Generated by Django 3.1.5 on 2021-01-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0036_auto_20210127_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_count',
        ),
    ]
