# Generated by Django 3.1.5 on 2021-01-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0037_remove_comment_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=48, verbose_name='제목'),
        ),
    ]
