# Generated by Django 3.1.5 on 2021-02-01 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0039_auto_20210127_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
