# Generated by Django 3.1.5 on 2021-02-03 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0041_video_dislike_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='save_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
